#!/usr/bin/python3
import py_compile
import os

# Get the path of the Python file from the environment variable
pyfile = os.environ.get('PYFILE')
cfile = pyfile + 'c'
# Compile the Python file
py_compile.compile(pyfile, cfile=cfile)
